import { createTypes } from 'reduxsauce'

export default createTypes(`
    FETCH_ORDERS_REQUEST
    FETCH_ORDERS_SUCCESS
    FETCH_ORDERS_FAILURE

    FETCH_SINGLE_CONTACT_REQUEST
    FETCH_SINGLE_CONTACT_SUCCESS
    FETCH_SINGLE_CONTACT_FAILURE
`);